package base;

import misc.Observable;
import misc.Observer;

/**
 * This is the final represented scene generated by the pcg system.
 */
public abstract class Scene extends Observable implements Observer {
  /**
   * The scene is generated from this model.
   */
  private final Model model;

  protected Scene(Model model) {
    this.model = model;
    model.addObserver(this);
  }

  public Model getModel() {
    return model;
  }
}
